# PyCity Schools Analysis

- Your analysis here

---

In [81]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path

# File to Load (Remember to Change These)
school_data_to_load = Path("Resources/schools_complete.csv")
student_data_to_load = Path("Resources/students_complete.csv")

# Read School and Student Data File and store into Pandas DataFrames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset.
school_data_complete = pd.merge(student_data, school_data, how="left", on="school_name")
school_data_complete.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635

## District Summary

In [82]:
# Calculate the total number of unique schools
school_count =len(school_data_complete["school_name"].value_counts())
school_count

15

In [83]:
# Calculate the total number of students
student_count =len(school_data_complete["Student ID"].value_counts())
student_count

39170

In [84]:
# Calculate the total budget
total_budget =school_data_complete["budget"].sum()
print(total_budget)

82932329558

In [85]:
# Calculate the average (mean) math score
average_math_score =school_data_complete["math_score"].mean()
print(average_math_score)

78.98537145774827

In [86]:
# Calculate the average (mean) reading score
average_reading_score =school_data_complete["reading_score"].mean()
print(average_reading_score)

81.87784018381414

In [87]:
# Use the following to calculate the percentage of students who passed math (math scores greather than or equal to 70)
passing_math_count = school_data_complete[(school_data_complete["math_score"] >= 70)].count()["student_name"]
passing_math_percentage = passing_math_count / float(student_count) * 100
print(passing_math_percentage)

74.9808526933878

In [88]:
# Calculate the percentage of students who passed reading (hint: look at how the math percentage was calculated)
passing_reading_count =school_data_complete[(school_data_complete["reading_score"] >= 70)].count()["student_name"]
passing_reading_percentage =passing_reading_count/ float(student_count) * 100
print(passing_reading_percentage)

85.80546336482001

In [89]:
# Use the following to calculate the percentage of students that passed math and reading
passing_math_reading_count = school_data_complete[
    (school_data_complete["math_score"] >= 70) & (school_data_complete["reading_score"] >= 70)
].count()["student_name"]
overall_passing_rate = passing_math_reading_count /  float(student_count) * 100
print(overall_passing_rate
)

65.17232575950983

In [90]:
# Create a high-level snapshot of the district's key metrics in a DataFrame
district_summary =pd.DataFrame({"Total Schools":[school_count],
                                "Total Students": student_count ,
                                 "Total Budget":total_budget,
                                 "Average Math Score":average_math_score,
                                 "Average Reading Score":average_reading_score,
                                 "% Passing Math":passing_math_percentage,
                                 "% Passing Reading	 ":passing_reading_percentage,
                                "% Overall Passing": overall_passing_rate
                                   }

)

# Formatting
district_summary["Total Students"] = district_summary["Total Students"].map("{:,}".format)
district_summary["Total Budget"] = district_summary["Total Budget"].map("${:,.2f}".format)

# Display the DataFrame
district_summary

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading\t,% Overall Passing
0,15,"39,170","$82,932,329,558.00",78.985371,81.87784,74.980853,85.805463,65.172326

## School Summary

In [91]:
# Use the code provided to select the type per school from school_data
school_types = school_data.set_index(["school_name"])["type"]
school_types

school_name
Huang High School        District
Figueroa High School     District
Shelton High School       Charter
Hernandez High School    District
Griffin High School       Charter
Wilson High School        Charter
Cabrera High School       Charter
Bailey High School       District
Holden High School        Charter
Pena High School          Charter
Wright High School        Charter
Rodriguez High School    District
Johnson High School      District
Ford High School         District
Thomas High School        Charter
Name: type, dtype: str

In [92]:
# Calculate the total student count per school from school_data
per_school_counts =school_data_complete["school_name"].value_counts()
per_school_counts

school_name
Bailey High School       4976
Johnson High School      4761
Hernandez High School    4635
Rodriguez High School    3999
Figueroa High School     2949
Huang High School        2917
Ford High School         2739
Wilson High School       2283
Cabrera High School      1858
Wright High School       1800
Shelton High School      1761
Thomas High School       1635
Griffin High School      1468
Pena High School          962
Holden High School        427
Name: count, dtype: int64

In [93]:
# Calculate the total school budget and per capita spending per school from school_data
total_school_budget = school_data["budget"].sum()

total_school_budget
per_school_budget = school_data.set_index("school_name")["budget"]


# 3. Per capita spending
per_school_capita = per_school_budget / per_school_counts

In [94]:
# Calculate the average test scores per school from school_data_complete
average_scores = school_data_complete.groupby("school_name").agg(
    Average_Math_Score=("math_score", "mean"),
    Average_Reading_Score=("reading_score", "mean")
)

print(average_scores)

                       Average_Math_Score  Average_Reading_Score
school_name
Bailey High School              77.048432              81.033963
Cabrera High School             83.061895              83.975780
Figueroa High School            76.711767              81.158020
Ford High School                77.102592              80.746258
Griffin High School             83.351499              83.816757
Hernandez High School           77.289752              80.934412
Holden High School              83.803279              83.814988
Huang High School               76.629414              81.182722
Johnson High School             77.072464              80.966394
Pena High School                83.839917              84.044699
Rodriguez High School           76.842711              80.744686
Shelton High School             83.359455              83.725724
Thomas High School              83.418349              83.848930
Wilson High School              83.274201              83.989488
Wright High School              83.682222              83.955000

In [95]:
# Calculate the number of students per school with math scores of 70 or higher from school_data_complete
school_students_passing_math = school_data_complete[
    school_data_complete["math_score"] >= 70
].count()["student_name"]
passing_math_per_school = school_data_complete[
    school_data_complete["math_score"] >= 70
].groupby("school_name")["student_name"].count()

print("total student passing maths :",school_students_passing_math)
print(passing_math_per_school)

total student passing maths : 29370
school_name
Bailey High School       3318
Cabrera High School      1749
Figueroa High School     1946
Ford High School         1871
Griffin High School      1371
Hernandez High School    3094
Holden High School        395
Huang High School        1916
Johnson High School      3145
Pena High School          910
Rodriguez High School    2654
Shelton High School      1653
Thomas High School       1525
Wilson High School       2143
Wright High School       1680
Name: student_name, dtype: int64

In [96]:
# Calculate the number of students per school with reading scores of 70 or higher from school_data_complete
school_students_passing_reading = school_data_complete[
    school_data_complete["reading_score"] >= 70
].count()["student_name"]
passing_reading_per_school = school_data_complete[
    school_data_complete["reading_score"] >= 70
].groupby("school_name")["student_name"].count()

print("total student passing reading :",school_students_passing_reading)
print(passing_reading_per_school)

total student passing reading : 33610
school_name
Bailey High School       4077
Cabrera High School      1803
Figueroa High School     2381
Ford High School         2172
Griffin High School      1426
Hernandez High School    3748
Holden High School        411
Huang High School        2372
Johnson High School      3867
Pena High School          923
Rodriguez High School    3208
Shelton High School      1688
Thomas High School       1591
Wilson High School       2204
Wright High School       1739
Name: student_name, dtype: int64

In [97]:
# Use the provided code to calculate the number of students per school that passed both math and reading with scores of 70 or higher
students_passing_math_and_reading = school_data_complete[
    (school_data_complete["reading_score"] >= 70) & (school_data_complete["math_score"] >= 70)
]
school_students_passing_math_and_reading = students_passing_math_and_reading.groupby(["school_name"]).size()
school_students_passing_math_and_reading

school_name
Bailey High School       2719
Cabrera High School      1697
Figueroa High School     1569
Ford High School         1487
Griffin High School      1330
Hernandez High School    2481
Holden High School        381
Huang High School        1561
Johnson High School      2549
Pena High School          871
Rodriguez High School    2119
Shelton High School      1583
Thomas High School       1487
Wilson High School       2068
Wright High School       1626
dtype: int64

In [98]:
# Use the provided code to calculate the passing rates
per_school_passing_math = school_students_passing_math / per_school_counts * 100
per_school_passing_reading = school_students_passing_reading / per_school_counts * 100
overall_passing_rate = school_students_passing_math_and_reading / per_school_counts * 100
passing_rates = pd.DataFrame({
    "Passing Math": per_school_passing_math,
    "Passing Reading": per_school_passing_reading,
    "Overall Passing": overall_passing_rate
})

passing_rates

                       Passing Math  Passing Reading  Overall Passing
school_name
Bailey High School       590.233119       675.442122        54.642283
Cabrera High School     1580.731970      1808.934338        91.334769
Figueroa High School     995.930824      1139.708376        53.204476
Ford High School        1072.289157      1227.090179        54.289887
Griffin High School     2000.681199      2289.509537        90.599455
Hernandez High School    633.656958       725.134844        53.527508
Holden High School      6878.220141      7871.194379        89.227166
Huang High School       1006.856359      1152.211176        53.513884
Johnson High School      616.887209       705.944129        53.539172
Pena High School        3053.014553      3493.762994        90.540541
Rodriguez High School    734.433608       840.460115        52.988247
Shelton High School     1667.802385      1908.574673        89.892107
Thomas High School      1796.330275      2055.657492        90.948012
Wilson High School      1286.465177      1472.185721        90.582567
Wright High School      1631.666667      1867.222222        90.333333

In [99]:
# Create a DataFrame called `per_school_summary` with columns for the calculations above.


per_school_summary = pd.DataFrame({
    "School Type": school_types,
    "Total Students": per_school_counts,
    "Total School Budget": per_school_budget,
    "Per Student Budget": per_school_capita,
    "Average Math Score": average_math_score,
    "Average Reading Score": average_reading_score,
    "% Passing Math": per_school_passing_math,
    "% Passing Reading": per_school_passing_reading,
    "% Overall Passing": overall_passing_rate
})

# Formatting
per_school_summary["Total School Budget"] = per_school_summary["Total School Budget"].map("${:,.2f}".format)

per_school_summary["Per Student Budget"] = per_school_summary["Per Student Budget"].map("${:,.2f}".format)

# Display
per_school_summary

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
school_name,,,,,,,,,
Bailey High School,District,4976,"$3,124,928.00",$628.00,78.985371,81.87784,590.233119,675.442122,54.642283
Cabrera High School,Charter,1858,"$1,081,356.00",$582.00,78.985371,81.87784,1580.731970,1808.934338,91.334769
Figueroa High School,District,2949,"$1,884,411.00",$639.00,78.985371,81.87784,995.930824,1139.708376,53.204476
Ford High School,District,2739,"$1,763,916.00",$644.00,78.985371,81.87784,1072.289157,1227.090179,54.289887
Griffin High School,Charter,1468,"$917,500.00",$625.00,78.985371,81.87784,2000.681199,2289.509537,90.599455
Hernandez High School,District,4635,"$3,022,020.00",$652.00,78.985371,81.87784,633.656958,725.134844,53.527508
Holden High School,Charter,427,"$248,087.00",$581.00,78.985371,81.87784,6878.220141,7871.194379,89.227166
Huang High School,District,2917,"$1,910,635.00",$655.00,78.985371,81.87784,1006.856359,1152.211176,53.513884
Johnson High School,District,4761,"$3,094,650.00",$650.00,78.985371,81.87784,616.887209,705.944129,53.539172
Pena High School,Charter,962,"$585,858.00",$609.00,78.985371,81.87784,3053.014553,3493.762994,90.540541
Rodriguez High School,District,3999,"$2,547,363.00",$637.00,78.985371,81.87784,734.433608,840.460115,52.988247
Shelton High School,Charter,1761,"$1,056,600.00",$600.00,78.985371,81.87784,1667.802385,1908.574673,89.892107
Thomas High School,Charter,1635,"$1,043,130.00",$638.00,78.985371,81.87784,1796.330275,2055.657492,90.948012
Wilson High School,Charter,2283,"$1,319,574.00",$578.00,78.985371,81.87784,1286.465177,1472.185721,90.582567
Wright High School,Charter,1800,"$1,049,400.00",$583.00,78.985371,81.87784,1631.666667,1867.222222,90.333333

## Highest-Performing Schools (by % Overall Passing)

In [100]:
# Sort the schools by `% Overall Passing` in descending order and display the top 5 rows.
top_schools = per_school_summary.sort_values(
    "% Overall Passing",
    ascending=False
)
top_schools.head(5)

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
school_name,,,,,,,,,
Cabrera High School,Charter,1858,"$1,081,356.00",$582.00,78.985371,81.87784,1580.731970,1808.934338,91.334769
Thomas High School,Charter,1635,"$1,043,130.00",$638.00,78.985371,81.87784,1796.330275,2055.657492,90.948012
Griffin High School,Charter,1468,"$917,500.00",$625.00,78.985371,81.87784,2000.681199,2289.509537,90.599455
Wilson High School,Charter,2283,"$1,319,574.00",$578.00,78.985371,81.87784,1286.465177,1472.185721,90.582567
Pena High School,Charter,962,"$585,858.00",$609.00,78.985371,81.87784,3053.014553,3493.762994,90.540541

## Bottom Performing Schools (By % Overall Passing)

In [101]:
# Sort the schools by `% Overall Passing` in ascending order and display the top 5 rows.
bottom_schools = per_school_summary.sort_values(
    "% Overall Passing",
    ascending=True
)
bottom_schools.head(5)

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
school_name,,,,,,,,,
Rodriguez High School,District,3999,"$2,547,363.00",$637.00,78.985371,81.87784,734.433608,840.460115,52.988247
Figueroa High School,District,2949,"$1,884,411.00",$639.00,78.985371,81.87784,995.930824,1139.708376,53.204476
Huang High School,District,2917,"$1,910,635.00",$655.00,78.985371,81.87784,1006.856359,1152.211176,53.513884
Hernandez High School,District,4635,"$3,022,020.00",$652.00,78.985371,81.87784,633.656958,725.134844,53.527508
Johnson High School,District,4761,"$3,094,650.00",$650.00,78.985371,81.87784,616.887209,705.944129,53.539172

## Math Scores by Grade

In [102]:
# Use the code provided to separate the data by grade
ninth_graders = school_data_complete[
    school_data_complete["grade"] == "9th"
]

tenth_graders = school_data_complete[
    school_data_complete["grade"] == "10th"
]

eleventh_graders = school_data_complete[
    school_data_complete["grade"] == "11th"
]

twelfth_graders = school_data_complete[
    school_data_complete["grade"] == "12th"
]


# Group by school_name and calculate the mean math score
ninth_grader_math_scores = ninth_graders.groupby(
    "school_name"
)["math_score"].mean()

tenth_grader_math_scores = tenth_graders.groupby(
    "school_name"
)["math_score"].mean()

eleventh_grader_math_scores = eleventh_graders.groupby(
    "school_name"
)["math_score"].mean()

twelfth_grader_math_scores = twelfth_graders.groupby(
    "school_name"
)["math_score"].mean()


# Combine all scores into one DataFrame
math_scores_by_grade = pd.DataFrame({
    "9th": ninth_grader_math_scores,
    "10th": tenth_grader_math_scores,
    "11th": eleventh_grader_math_scores,
    "12th": twelfth_grader_math_scores
})


# Minor data wrangling
math_scores_by_grade.index.name = None


# Display the DataFrame
math_scores_by_grade

                             9th       10th       11th       12th
Bailey High School     77.083676  76.996772  77.515588  76.492218
Cabrera High School    83.094697  83.154506  82.765560  83.277487
Figueroa High School   76.403037  76.539974  76.884344  77.151369
Ford High School       77.361345  77.672316  76.918058  76.179963
Griffin High School    82.044010  84.229064  83.842105  83.356164
Hernandez High School  77.438495  77.337408  77.136029  77.186567
Holden High School     83.787402  83.429825  85.000000  82.855422
Huang High School      77.027251  75.908735  76.446602  77.225641
Johnson High School    77.187857  76.691117  77.491653  76.863248
Pena High School       83.625455  83.372000  84.328125  84.121547
Rodriguez High School  76.859966  76.612500  76.395626  77.690748
Shelton High School    83.420755  82.917411  83.383495  83.778976
Thomas High School     83.590022  83.087886  83.498795  83.497041
Wilson High School     83.085578  83.724422  83.195326  83.035794
Wright High School     83.264706  84.010288  83.836782  83.644986

## Reading Score by Grade

In [103]:
# Use the code provided to separate the data by grade
ninth_graders = school_data_complete[(school_data_complete["grade"] == "9th")]
tenth_graders = school_data_complete[(school_data_complete["grade"] == "10th")]
eleventh_graders = school_data_complete[(school_data_complete["grade"] == "11th")]
twelfth_graders = school_data_complete[(school_data_complete["grade"] == "12th")]

# Group by `school_name` and take the mean of the the `reading_score` column for each.
ninth_grade_reading_scores =ninth_graders.groupby("school_name")["reading_score"].mean()
tenth_grader_reading_scores =tenth_graders.groupby("school_name")["reading_score"].mean()
eleventh_grader_reading_scores =eleventh_graders.groupby("school_name")["reading_score"].mean()
twelfth_grader_reading_scores =twelfth_graders.groupby("school_name")["reading_score"].mean()

# Combine each of the scores above into single DataFrame called `reading_scores_by_grade`
reading_scores_by_grade =pd.DataFrame({"9th": ninth_grader_math_scores,
    "10th": tenth_grader_reading_scores,
    "11th": eleventh_grader_reading_scores,
    "12th": twelfth_grader_reading_scores})

# Minor data wrangling
reading_scores_by_grade = reading_scores_by_grade[["9th", "10th", "11th", "12th"]]
reading_scores_by_grade.index.name = None

# Display the DataFrame
reading_scores_by_grade

                             9th       10th       11th       12th
Bailey High School     77.083676  80.907183  80.945643  80.912451
Cabrera High School    83.094697  84.253219  83.788382  84.287958
Figueroa High School   76.403037  81.408912  80.640339  81.384863
Ford High School       77.361345  81.262712  80.403642  80.662338
Griffin High School    82.044010  83.706897  84.288089  84.013699
Hernandez High School  77.438495  80.660147  81.396140  80.857143
Holden High School     83.787402  83.324561  83.815534  84.698795
Huang High School      77.027251  81.512386  81.417476  80.305983
Johnson High School    77.187857  80.773431  80.616027  81.227564
Pena High School       83.625455  83.612000  84.335938  84.591160
Rodriguez High School  76.859966  80.629808  80.864811  80.376426
Shelton High School    83.420755  83.441964  84.373786  82.781671
Thomas High School     83.590022  84.254157  83.585542  83.831361
Wilson High School     83.085578  84.021452  83.764608  84.317673
Wright High School     83.264706  83.812757  84.156322  84.073171

## Scores by School Spending

In [104]:
# Establish the bins
spending_bins = [0, 585, 630, 645, 680]
labels = ["<$585", "$585-630", "$630-645", "$645-680"]

In [105]:
# Create a copy of the school summary for later aggregations
school_spending_df = per_school_summary.copy()

In [106]:
# Use `pd.cut` on the per_school_capita Series from earlier to categorize per student spending based on the bins.
school_spending_df["Spending Ranges (Per Student)"] =pd.cut(
    per_school_capita,
    bins=spending_bins,
    labels=labels
)

# Convert Spending Ranges (Per Student) to a string
school_spending_df["Spending Ranges (Per Student)"] = school_spending_df["Spending Ranges (Per Student)"].astype(str)
school_spending_df

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing,Spending Ranges (Per Student)
school_name,,,,,,,,,,
Bailey High School,District,4976,"$3,124,928.00",$628.00,78.985371,81.87784,590.233119,675.442122,54.642283,$585-630
Cabrera High School,Charter,1858,"$1,081,356.00",$582.00,78.985371,81.87784,1580.731970,1808.934338,91.334769,<$585
Figueroa High School,District,2949,"$1,884,411.00",$639.00,78.985371,81.87784,995.930824,1139.708376,53.204476,$630-645
Ford High School,District,2739,"$1,763,916.00",$644.00,78.985371,81.87784,1072.289157,1227.090179,54.289887,$630-645
Griffin High School,Charter,1468,"$917,500.00",$625.00,78.985371,81.87784,2000.681199,2289.509537,90.599455,$585-630
Hernandez High School,District,4635,"$3,022,020.00",$652.00,78.985371,81.87784,633.656958,725.134844,53.527508,$645-680
Holden High School,Charter,427,"$248,087.00",$581.00,78.985371,81.87784,6878.220141,7871.194379,89.227166,<$585
Huang High School,District,2917,"$1,910,635.00",$655.00,78.985371,81.87784,1006.856359,1152.211176,53.513884,$645-680
Johnson High School,District,4761,"$3,094,650.00",$650.00,78.985371,81.87784,616.887209,705.944129,53.539172,$645-680
Pena High School,Charter,962,"$585,858.00",$609.00,78.985371,81.87784,3053.014553,3493.762994,90.540541,$585-630
Rodriguez High School,District,3999,"$2,547,363.00",$637.00,78.985371,81.87784,734.433608,840.460115,52.988247,$630-645
Shelton High School,Charter,1761,"$1,056,600.00",$600.00,78.985371,81.87784,1667.802385,1908.574673,89.892107,$585-630
Thomas High School,Charter,1635,"$1,043,130.00",$638.00,78.985371,81.87784,1796.330275,2055.657492,90.948012,$630-645
Wilson High School,Charter,2283,"$1,319,574.00",$578.00,78.985371,81.87784,1286.465177,1472.185721,90.582567,<$585
Wright High School,Charter,1800,"$1,049,400.00",$583.00,78.985371,81.87784,1631.666667,1867.222222,90.333333,<$585

In [107]:
#  Calculate averages for the desired columns.
spending_math_scores = school_spending_df.groupby(["Spending Ranges (Per Student)"])["Average Math Score"].mean()
spending_reading_scores = school_spending_df.groupby(["Spending Ranges (Per Student)"])["Average Reading Score"].mean()
spending_passing_math = school_spending_df.groupby(["Spending Ranges (Per Student)"])["% Passing Math"].mean()
spending_passing_reading = school_spending_df.groupby(["Spending Ranges (Per Student)"])["% Passing Reading"].mean()
overall_passing_spending = school_spending_df.groupby(["Spending Ranges (Per Student)"])["% Overall Passing"].mean()

In [108]:
# Assemble into DataFrame

spending_summary = pd.DataFrame({
    "Spending Ranges (Per Student)": labels,
    "Average Math Score": spending_math_scores,
    "Average Reading Score": spending_reading_scores,
    "% Passing Math": spending_passing_math,
    "% Passing Reading": spending_passing_reading,
    "% Overall Passing": overall_passing_spending
})

# Display results
spending_summary

,Spending Ranges (Per Student),Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
Spending Ranges (Per Student),,,,,,
$585-630,<$585,78.985371,81.87784,1827.932814,2091.822332,81.418596
$630-645,$585-630,78.985371,81.87784,1149.745966,1315.729041,62.857656
$645-680,$630-645,78.985371,81.87784,752.466842,861.096716,53.526855
<$585,$645-680,78.985371,81.87784,2844.270989,3254.884165,90.369459

## Scores by School Size

In [109]:
# Establish the bins.
size_bins = [0, 1000, 2000, 5000]
labels = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]

In [110]:
# Create a copy of the school summary for later aggregations
school_size_df = per_school_summary.copy()

In [111]:
# Use `pd.cut` on the per_school_counts Series from earlier to categorize school size based on the bins.
school_size_df["School Size"] =pd.cut(
    per_school_counts,
    bins=size_bins,
    labels=labels
)

# Convert School Size to a string
school_size_df["School Size"] = school_size_df["School Size"].astype(str)
school_size_df

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing,School Size
school_name,,,,,,,,,,
Bailey High School,District,4976,"$3,124,928.00",$628.00,78.985371,81.87784,590.233119,675.442122,54.642283,Large (2000-5000)
Cabrera High School,Charter,1858,"$1,081,356.00",$582.00,78.985371,81.87784,1580.731970,1808.934338,91.334769,Medium (1000-2000)
Figueroa High School,District,2949,"$1,884,411.00",$639.00,78.985371,81.87784,995.930824,1139.708376,53.204476,Large (2000-5000)
Ford High School,District,2739,"$1,763,916.00",$644.00,78.985371,81.87784,1072.289157,1227.090179,54.289887,Large (2000-5000)
Griffin High School,Charter,1468,"$917,500.00",$625.00,78.985371,81.87784,2000.681199,2289.509537,90.599455,Medium (1000-2000)
Hernandez High School,District,4635,"$3,022,020.00",$652.00,78.985371,81.87784,633.656958,725.134844,53.527508,Large (2000-5000)
Holden High School,Charter,427,"$248,087.00",$581.00,78.985371,81.87784,6878.220141,7871.194379,89.227166,Small (<1000)
Huang High School,District,2917,"$1,910,635.00",$655.00,78.985371,81.87784,1006.856359,1152.211176,53.513884,Large (2000-5000)
Johnson High School,District,4761,"$3,094,650.00",$650.00,78.985371,81.87784,616.887209,705.944129,53.539172,Large (2000-5000)
Pena High School,Charter,962,"$585,858.00",$609.00,78.985371,81.87784,3053.014553,3493.762994,90.540541,Small (<1000)
Rodriguez High School,District,3999,"$2,547,363.00",$637.00,78.985371,81.87784,734.433608,840.460115,52.988247,Large (2000-5000)
Shelton High School,Charter,1761,"$1,056,600.00",$600.00,78.985371,81.87784,1667.802385,1908.574673,89.892107,Medium (1000-2000)
Thomas High School,Charter,1635,"$1,043,130.00",$638.00,78.985371,81.87784,1796.330275,2055.657492,90.948012,Medium (1000-2000)
Wilson High School,Charter,2283,"$1,319,574.00",$578.00,78.985371,81.87784,1286.465177,1472.185721,90.582567,Large (2000-5000)
Wright High School,Charter,1800,"$1,049,400.00",$583.00,78.985371,81.87784,1631.666667,1867.222222,90.333333,Medium (1000-2000)

In [112]:
# Calculate averages for the desired columns.
size_math_scores = school_size_df.groupby(["School Size"])["Average Math Score"].mean()
size_reading_scores = school_size_df.groupby(["School Size"])["Average Reading Score"].mean()
size_passing_math = school_size_df.groupby(["School Size"])["% Passing Math"].mean()
size_passing_reading = school_size_df.groupby(["School Size"])["% Passing Reading"].mean()
size_overall_passing = school_size_df.groupby(["School Size"])["% Overall Passing"].mean()

In [113]:
# Create a DataFrame called `size_summary` that breaks down school performance based on school size (small, medium, or large).
# Use the scores above to create a new DataFrame called `size_summary`
size_summary = pd.DataFrame(
    {
        "School Size": labels,
        "Average Math Score":size_math_scores,
        "Average Reading Score":size_reading_scores,
        "% Passing Math":size_passing_math,
        "% Passing Reading":size_passing_reading,
        "% Overall Passing":size_overall_passing

    }
)

# Display results
size_summary

,School Size,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
School Size,,,,,,
Large (2000-5000),Small (<1000),78.985371,81.87784,867.094051,992.272083,58.286003
Medium (1000-2000),Medium (1000-2000),78.985371,81.87784,1735.442499,1985.979653,90.621535
Small (<1000),Large (2000-5000),78.985371,81.87784,4965.617347,5682.478687,89.883853

## Scores by School Type

In [114]:
# Group the per_school_summary DataFrame by "School Type" and average the results.
average_math_score_by_type = per_school_summary.groupby(["School Type"])["Average Math Score"].mean()
average_reading_score_by_type = per_school_summary.groupby(["School Type"])["Average Reading Score"].mean()
average_percent_passing_math_by_type = per_school_summary.groupby(["School Type"])["% Passing Math"].mean()
average_percent_passing_reading_by_type = per_school_summary.groupby(["School Type"])["% Passing Reading"].mean()
average_percent_overall_passing_by_type = per_school_summary.groupby(["School Type"])["% Overall Passing"].mean()

In [117]:
# Assemble the new data by type into a DataFrame called `type_summary`
type_summary =pd.DataFrame(
    {
        
        "Average Math Score":average_math_score_by_type,
        "Average Reading Score":average_reading_score_by_type,
        "% Passing Math":average_percent_passing_math_by_type,
        "% Passing Reading":average_percent_passing_reading_by_type,
        "% Overall Passing":average_percent_overall_passing_by_type
    }
)

# Display results
type_summary

,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
School Type,,,,,
Charter,78.985371,81.87784,2486.864046,2845.880170,90.432244
District,78.985371,81.87784,807.183891,923.712992,53.672208